name: 15-minute-cron
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://harmon-avusnce2u-harmonie.vercel.app/api/global-doc-index-to-algolia' \
          --header 'Authorization: Bearer ${{ secrets.CRON_KEY }}'